runtime: python37

handlers:
# mappings are matched in order of declaration

- url: /api/.*
  secure: always
  redirect_http_response_code: 301
  script: auto

- url: /(.+)
  static_files: docroot/\1
  upload: docroot/(.+)

- url: /
  static_files: docroot/index.html
  upload: docroot/index.html




  